#!/bin/bash
rm -rf dist
VERSION=`git describe --tags`
python2 setup-release.py py2app
hdiutil create -fs HFS+ -volname "Electrum-ZENY" -srcfolder dist/Electrum-ZENY.app dist/electrum-zeny-$VERSION.dmg

